/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.soulappsworld.flashlights;

public final class R {
    public static final class attr {
        /** 
    The size of the ad. It must be one of BANNER, FULL_BANNER, LEADERBOARD,
    MEDIUM_RECTANGLE, SMART_BANNER, WIDE_SKYSCRAPER, or
    &lt;width&gt;x&lt;height&gt;.
    
         <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int adSize=0x7f010000;
        /** 
    A comma-separated list of the supported ad sizes. The sizes must be one of
    BANNER, FULL_BANNER, LEADERBOARD, MEDIUM_RECTANGLE, SMART_BANNER,
    WIDE_SKYSCRAPER, or &lt;width&gt;x&lt;height&gt;.
    
         <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int adSizes=0x7f010001;
        /**  The ad unit ID. 
         <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int adUnitId=0x7f010002;
        /**  Appearance of the buy button. Must be one of "classic", "grayscale" and "monochrome" 
         <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>classic</code></td><td>1</td><td></td></tr>
<tr><td><code>grayscale</code></td><td>2</td><td></td></tr>
<tr><td><code>monochrome</code></td><td>3</td><td></td></tr>
</table>
         */
        public static final int buyButtonAppearance=0x7f010018;
        /**  Height of the buy button. This includes an 8dp padding (4dp on each side) used for
             pressed and focused states of the button. The value can be a specific height, e.g.
             "48dp", or special values "match_parent" and "wrap_content". 
         <p>May be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
<p>May be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>match_parent</code></td><td>-1</td><td></td></tr>
<tr><td><code>wrap_content</code></td><td>-2</td><td></td></tr>
</table>
         */
        public static final int buyButtonHeight=0x7f010015;
        /**  Text on the buy button. Must be one of "buy_with_google", "buy_now" and "book_now" 
         <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>buy_with_google</code></td><td>1</td><td></td></tr>
<tr><td><code>buy_now</code></td><td>2</td><td></td></tr>
<tr><td><code>book_now</code></td><td>3</td><td></td></tr>
</table>
         */
        public static final int buyButtonText=0x7f010017;
        /**  Width of the buy button. This includes an 8dp padding (4dp on each side) used for
             pressed and focused states of the button. The value can be a specific width, e.g.
             "300dp", or special values "match_parent" and "wrap_content". 
         <p>May be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
<p>May be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>match_parent</code></td><td>-1</td><td></td></tr>
<tr><td><code>wrap_content</code></td><td>-2</td><td></td></tr>
</table>
         */
        public static final int buyButtonWidth=0x7f010016;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int cameraBearing=0x7f010004;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int cameraTargetLat=0x7f010005;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int cameraTargetLng=0x7f010006;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int cameraTilt=0x7f010007;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int cameraZoom=0x7f010008;
        /**  Google Wallet environment to use 
         <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>production</code></td><td>1</td><td></td></tr>
<tr><td><code>sandbox</code></td><td>0</td><td></td></tr>
<tr><td><code>strict_sandbox</code></td><td>2</td><td></td></tr>
</table>
         */
        public static final int environment=0x7f010012;
        /**  Fragment mode 
         <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>buyButton</code></td><td>1</td><td></td></tr>
<tr><td><code>selectionDetails</code></td><td>2</td><td></td></tr>
</table>
         */
        public static final int fragmentMode=0x7f010014;
        /**  A style resource specifing attributes to customize the look and feel of WalletFragment 
         <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int fragmentStyle=0x7f010013;
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>none</code></td><td>0</td><td></td></tr>
<tr><td><code>normal</code></td><td>1</td><td></td></tr>
<tr><td><code>satellite</code></td><td>2</td><td></td></tr>
<tr><td><code>terrain</code></td><td>3</td><td></td></tr>
<tr><td><code>hybrid</code></td><td>4</td><td></td></tr>
</table>
         */
        public static final int mapType=0x7f010003;
        /**  Masked wallet details background 
         <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
         */
        public static final int maskedWalletDetailsBackground=0x7f01001b;
        /**  "Change" button background in masked wallet details view 
         <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
         */
        public static final int maskedWalletDetailsButtonBackground=0x7f01001d;
        /**  TextAppearance for the "Change" button in masked wallet details view 
         <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int maskedWalletDetailsButtonTextAppearance=0x7f01001c;
        /**  TextAppearance for headers describing masked wallet details 
         <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int maskedWalletDetailsHeaderTextAppearance=0x7f01001a;
        /**  Type of the wallet logo image in masked wallet details view 
         <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>classic</code></td><td>1</td><td></td></tr>
<tr><td><code>monochrome</code></td><td>2</td><td></td></tr>
</table>
         */
        public static final int maskedWalletDetailsLogoImageType=0x7f01001f;
        /**  Color of the Google Wallet logo text in masked wallet details view 
         <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int maskedWalletDetailsLogoTextColor=0x7f01001e;
        /**  TextAppearance for masked wallet details 
         <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int maskedWalletDetailsTextAppearance=0x7f010019;
        /**  Theme to be used for the Wallet selector 
         <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>holo_dark</code></td><td>0</td><td></td></tr>
<tr><td><code>holo_light</code></td><td>1</td><td></td></tr>
</table>
         */
        public static final int theme=0x7f010011;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int uiCompass=0x7f010009;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int uiRotateGestures=0x7f01000a;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int uiScrollGestures=0x7f01000b;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int uiTiltGestures=0x7f01000c;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int uiZoomControls=0x7f01000d;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int uiZoomGestures=0x7f01000e;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int useViewLifecycle=0x7f01000f;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int zOrderOnTop=0x7f010010;
    }
    public static final class color {
        public static final int backgraycolor=0x7f06001c;
        public static final int backgroundblackcolor=0x7f060019;
        public static final int backgroundwhitecolor=0x7f060018;
        public static final int common_action_bar_splitter=0x7f060009;
        /**  Sign-in Button Colors 
         */
        public static final int common_signin_btn_dark_text_default=0x7f060000;
        public static final int common_signin_btn_dark_text_disabled=0x7f060002;
        public static final int common_signin_btn_dark_text_focused=0x7f060003;
        public static final int common_signin_btn_dark_text_pressed=0x7f060001;
        public static final int common_signin_btn_default_background=0x7f060008;
        public static final int common_signin_btn_light_text_default=0x7f060004;
        public static final int common_signin_btn_light_text_disabled=0x7f060006;
        public static final int common_signin_btn_light_text_focused=0x7f060007;
        public static final int common_signin_btn_light_text_pressed=0x7f060005;
        public static final int common_signin_btn_text_dark=0x7f06001d;
        public static final int common_signin_btn_text_light=0x7f06001e;
        public static final int textblackcolor=0x7f06001b;
        public static final int textcolor=0x7f060017;
        public static final int textwhitecolor=0x7f06001a;
        public static final int wallet_bright_foreground_disabled_holo_light=0x7f06000f;
        /** 
         Wallet colors to support consistent Wallet fragment holo dark UI in client application
         regardless of the theme and device type
    
         */
        public static final int wallet_bright_foreground_holo_dark=0x7f06000a;
        public static final int wallet_bright_foreground_holo_light=0x7f060010;
        public static final int wallet_dim_foreground_disabled_holo_dark=0x7f06000c;
        public static final int wallet_dim_foreground_holo_dark=0x7f06000b;
        public static final int wallet_dim_foreground_inverse_disabled_holo_dark=0x7f06000e;
        public static final int wallet_dim_foreground_inverse_holo_dark=0x7f06000d;
        public static final int wallet_highlighted_text_holo_dark=0x7f060014;
        public static final int wallet_highlighted_text_holo_light=0x7f060013;
        public static final int wallet_hint_foreground_holo_dark=0x7f060012;
        public static final int wallet_hint_foreground_holo_light=0x7f060011;
        public static final int wallet_holo_blue_light=0x7f060015;
        public static final int wallet_link_text_light=0x7f060016;
        public static final int wallet_primary_text_holo_light=0x7f06001f;
        public static final int wallet_secondary_text_holo_dark=0x7f060020;
    }
    public static final class dimen {
        public static final int padding_large=0x7f090002;
        public static final int padding_medium=0x7f090001;
        public static final int padding_small=0x7f090000;
        public static final int textdoubleextralargesize=0x7f090007;
        public static final int textextralargesize=0x7f090006;
        public static final int textlargesize=0x7f090005;
        public static final int textnormalsize=0x7f090004;
        public static final int textsmallsize=0x7f090003;
        public static final int texttripleextralargesize=0x7f090008;
    }
    public static final class drawable {
        public static final int arrow=0x7f020000;
        public static final int arrow_400x600=0x7f020001;
        public static final int back_2=0x7f020002;
        public static final int back_2hover=0x7f020003;
        public static final int backchangeimage=0x7f020004;
        public static final int background=0x7f020005;
        public static final int background_800_1200=0x7f020006;
        public static final int bg_change_image=0x7f020007;
        public static final int bg_color_32x32=0x7f020008;
        public static final int blinking_change_image=0x7f020009;
        public static final int bluebutton_change_image=0x7f02000a;
        public static final int button_black=0x7f02000b;
        public static final int button_blue=0x7f02000c;
        public static final int common_signin_btn_icon_dark=0x7f02000d;
        public static final int common_signin_btn_icon_disabled_dark=0x7f02000e;
        public static final int common_signin_btn_icon_disabled_focus_dark=0x7f02000f;
        public static final int common_signin_btn_icon_disabled_focus_light=0x7f020010;
        public static final int common_signin_btn_icon_disabled_light=0x7f020011;
        public static final int common_signin_btn_icon_focus_dark=0x7f020012;
        public static final int common_signin_btn_icon_focus_light=0x7f020013;
        public static final int common_signin_btn_icon_light=0x7f020014;
        public static final int common_signin_btn_icon_normal_dark=0x7f020015;
        public static final int common_signin_btn_icon_normal_light=0x7f020016;
        public static final int common_signin_btn_icon_pressed_dark=0x7f020017;
        public static final int common_signin_btn_icon_pressed_light=0x7f020018;
        public static final int common_signin_btn_text_dark=0x7f020019;
        public static final int common_signin_btn_text_disabled_dark=0x7f02001a;
        public static final int common_signin_btn_text_disabled_focus_dark=0x7f02001b;
        public static final int common_signin_btn_text_disabled_focus_light=0x7f02001c;
        public static final int common_signin_btn_text_disabled_light=0x7f02001d;
        public static final int common_signin_btn_text_focus_dark=0x7f02001e;
        public static final int common_signin_btn_text_focus_light=0x7f02001f;
        public static final int common_signin_btn_text_light=0x7f020020;
        public static final int common_signin_btn_text_normal_dark=0x7f020021;
        public static final int common_signin_btn_text_normal_light=0x7f020022;
        public static final int common_signin_btn_text_pressed_dark=0x7f020023;
        public static final int common_signin_btn_text_pressed_light=0x7f020024;
        public static final int flashlight_32x32=0x7f020025;
        public static final int header_back=0x7f020026;
        public static final int i_32x32=0x7f020027;
        public static final int i_32x32_=0x7f020028;
        public static final int ic_launcher=0x7f020029;
        public static final int ic_plusone_medium_off_client=0x7f02002a;
        public static final int ic_plusone_small_off_client=0x7f02002b;
        public static final int ic_plusone_standard_off_client=0x7f02002c;
        public static final int ic_plusone_tall_off_client=0x7f02002d;
        public static final int icon=0x7f02002e;
        public static final int icon_200x200=0x7f02002f;
        public static final int icon_500x500=0x7f020030;
        public static final int icon_bg_color_100x100=0x7f020031;
        public static final int icon_bg_color_150x150=0x7f020032;
        public static final int icon_bg_color_click_100x100=0x7f020033;
        public static final int icon_flashlight_100x100=0x7f020034;
        public static final int icon_flashlight_150x150=0x7f020035;
        public static final int icon_flashlight_click_100x100=0x7f020036;
        public static final int icon_police_light_100x100=0x7f020037;
        public static final int icon_police_light_150x150=0x7f020038;
        public static final int icon_police_light_click_100x100=0x7f020039;
        public static final int icon_screen_lgt_100x100=0x7f02003a;
        public static final int icon_screen_lgt_150x150=0x7f02003b;
        public static final int icon_screen_lgt_click_100x100_=0x7f02003c;
        public static final int icon_torch_100x100=0x7f02003d;
        public static final int icon_torch_150x150=0x7f02003e;
        public static final int icon_torch_click_100x100=0x7f02003f;
        public static final int icon_trafic_100x100=0x7f020040;
        public static final int icon_trafic_150x150=0x7f020041;
        public static final int icon_trafic_click_100x100=0x7f020042;
        public static final int info_change_image=0x7f020043;
        public static final int lgt_start=0x7f020044;
        public static final int lgt_stop=0x7f020045;
        public static final int line=0x7f020046;
        public static final int more_app_icon=0x7f020047;
        public static final int police_change_image=0x7f020048;
        public static final int police_light_32x32=0x7f020049;
        public static final int powered_by_google_dark=0x7f02004a;
        public static final int powered_by_google_light=0x7f02004b;
        public static final int ring_400x600=0x7f02004c;
        public static final int ring_800x1200=0x7f02004d;
        public static final int screen_lgt_32x32=0x7f02004e;
        public static final int screen_lgt_change_image=0x7f02004f;
        public static final int screenlgt=0x7f020050;
        public static final int screenlgt_=0x7f020051;
        public static final int scroll_button=0x7f020052;
        public static final int seekbar_progress=0x7f020053;
        public static final int seekbar_progress_bg=0x7f020054;
        public static final int setting_change_image=0x7f020055;
        public static final int settings_icon_32x32=0x7f020056;
        public static final int settings_icon_32x32_=0x7f020057;
        public static final int shape=0x7f020058;
        public static final int torch_change_image=0x7f020059;
        public static final int torch_icon_32x32=0x7f02005a;
        public static final int traffic_change_image=0x7f02005b;
        public static final int traffic_icon_32x32=0x7f02005c;
        public static final int trafic=0x7f02005d;
        public static final int trafic_green=0x7f02005e;
        public static final int trafic_red=0x7f02005f;
        public static final int trafic_yellow=0x7f020060;
    }
    public static final class id {
        public static final int adView=0x7f070015;
        public static final int appname=0x7f07003b;
        public static final int arrow=0x7f07003c;
        public static final int blinkingsurfaceView=0x7f070021;
        public static final int book_now=0x7f070010;
        public static final int btn_Buy_PRO=0x7f07002c;
        public static final int buyButton=0x7f07000a;
        public static final int buy_now=0x7f07000f;
        public static final int buy_with_google=0x7f07000e;
        public static final int classic=0x7f070011;
        public static final int edtName=0x7f07001b;
        public static final int fl_header_layout=0x7f070035;
        public static final int grayscale=0x7f070012;
        public static final int holo_dark=0x7f070005;
        public static final int holo_light=0x7f070006;
        public static final int hybrid=0x7f070004;
        public static final int imgappicon=0x7f07003a;
        public static final int imgbtnback=0x7f070033;
        public static final int imgbtnflashlgt=0x7f070025;
        public static final int imgbtnflashlgtblnk=0x7f07002a;
        public static final int imgbtnfunction=0x7f070039;
        public static final int imgbtninfo=0x7f070038;
        public static final int imgbtnpolicelight=0x7f070026;
        public static final int imgbtnscreenbackground=0x7f07002b;
        public static final int imgbtnscreenlgt=0x7f070027;
        public static final int imgbtnsetting=0x7f070036;
        public static final int imgbtnsimpleflashlgt=0x7f07002f;
        public static final int imgbtntraficlgt=0x7f070032;
        public static final int imgbtntraficsignallgt=0x7f070028;
        public static final int imgsplashicon=0x7f070017;
        public static final int llarrow=0x7f07001d;
        public static final int llbackgroundmainlayout=0x7f07001c;
        public static final int llflashlgt=0x7f070024;
        public static final int llflashlgtblnk=0x7f070029;
        public static final int llmainactivity=0x7f070022;
        public static final int llpolicelgt=0x7f07002d;
        public static final int llscrren_lgt=0x7f07002e;
        public static final int llspashscreen=0x7f070016;
        public static final int lltraficlgt=0x7f070031;
        public static final int lstAbout=0x7f070014;
        public static final int match_parent=0x7f07000c;
        public static final int menu_settings=0x7f07003d;
        public static final int monochrome=0x7f070013;
        public static final int none=0x7f070000;
        public static final int normal=0x7f070001;
        public static final int production=0x7f070007;
        public static final int sandbox=0x7f070008;
        public static final int satellite=0x7f070002;
        public static final int selectionDetails=0x7f07000b;
        public static final int skbarview=0x7f070020;
        public static final int stopscanheader=0x7f070023;
        public static final int strict_sandbox=0x7f070009;
        public static final int surfaceView=0x7f070030;
        public static final int terrain=0x7f070003;
        public static final int txtFlashlight=0x7f070018;
        public static final int txtTorch=0x7f07001a;
        public static final int txtheadingname=0x7f070037;
        public static final int txtinfoname=0x7f070034;
        public static final int txtplus=0x7f070019;
        public static final int txtswap1=0x7f07001e;
        public static final int txtswap2=0x7f07001f;
        public static final int wrap_content=0x7f07000d;
    }
    public static final class integer {
        public static final int google_play_services_version=0x7f080000;
    }
    public static final class layout {
        public static final int aboutus=0x7f030000;
        public static final int activity_ft__splash_screen=0x7f030001;
        public static final int edit=0x7f030002;
        public static final int ft_background=0x7f030003;
        public static final int ft_flashlight_blinking=0x7f030004;
        public static final int ft_main_activity=0x7f030005;
        public static final int ft_main_activity_2=0x7f030006;
        public static final int ft_police_light=0x7f030007;
        public static final int ft_screen_light=0x7f030008;
        public static final int ft_setting=0x7f030009;
        public static final int ft_simple_flashlight=0x7f03000a;
        public static final int ft_traffic_signal=0x7f03000b;
        public static final int header_info=0x7f03000c;
        public static final int header_layout=0x7f03000d;
        public static final int header_layout_2=0x7f03000e;
        public static final int row_about=0x7f03000f;
    }
    public static final class menu {
        public static final int activity_ft__splash_screen=0x7f0a0000;
    }
    public static final class string {
        public static final int About_US=0x7f05002b;
        public static final int About_US_link=0x7f050048;
        public static final int Ancient_Islamic_Wallpaper=0x7f050033;
        public static final int BMI_Calculator=0x7f050034;
        public static final int Battery_Saver=0x7f050035;
        public static final int Call_Recorder=0x7f050036;
        public static final int Cancel=0x7f050030;
        public static final int Color_Light=0x7f050027;
        public static final int Compass_HD=0x7f050037;
        public static final int ContactUS=0x7f050049;
        public static final int Contact_from=0x7f05004a;
        public static final int File_Manager=0x7f050047;
        public static final int FlashLight_Blinking=0x7f050024;
        public static final int Flashlight=0x7f050021;
        public static final int Flashlight_torch=0x7f050038;
        public static final int Info=0x7f05002c;
        public static final int IslamicWallpaperHD=0x7f05003a;
        public static final int Islamic_Compass=0x7f050039;
        public static final int Islamic_Dictionary=0x7f050045;
        public static final int MoreApps=0x7f050032;
        public static final int MyStamps=0x7f05003b;
        public static final int My_Text_Live=0x7f05003c;
        public static final int No_Internet_Connection=0x7f05002d;
        public static final int OK=0x7f05002e;
        public static final int Police_Light=0x7f050026;
        public static final int QR_BARCODE_SCANNER=0x7f050044;
        public static final int Rate_This_App=0x7f050031;
        public static final int Screen_Light=0x7f050023;
        public static final int Send=0x7f05002f;
        public static final int Share_Andoird=0x7f05004c;
        public static final int Share_App=0x7f05004b;
        public static final int Share_App_Body_bottom=0x7f050051;
        public static final int Share_App_Body_middle=0x7f050050;
        public static final int Share_App_Body_top=0x7f05004f;
        public static final int Share_App_subject=0x7f05004e;
        public static final int Share_Application=0x7f05004d;
        public static final int Smart_Uninstaller=0x7f050046;
        public static final int SocialWorldApp=0x7f05003d;
        public static final int Speedometer=0x7f050043;
        public static final int Stopwatch_Timer=0x7f05003e;
        public static final int Swipe_to_change=0x7f050028;
        public static final int Torch=0x7f050022;
        public static final int Traffic_Light=0x7f050025;
        public static final int Valentine_Day_Special=0x7f050040;
        public static final int Valentine_Live_Wallpaper=0x7f05003f;
        public static final int Voice_Recorder=0x7f050041;
        public static final int app_name=0x7f050020;
        public static final int auth_client_needs_enabling_title=0x7f050001;
        public static final int auth_client_needs_installation_title=0x7f050002;
        public static final int auth_client_needs_update_title=0x7f050003;
        public static final int auth_client_play_services_err_notification_msg=0x7f050004;
        public static final int auth_client_requested_by_msg=0x7f050005;
        public static final int auth_client_using_bad_version_title=0x7f050000;
        public static final int brightness_and_color=0x7f050029;
        /**  Button in confirmation dialog to enable Google Play services.  Clicking it
        will direct user to application settings of Google Play services where they
        can enable it [CHAR LIMIT=40] 
         */
        public static final int common_google_play_services_enable_button=0x7f050011;
        /**  Message in confirmation dialog informing user they need to enable
        Google Play services in application settings [CHAR LIMIT=NONE] 
         */
        public static final int common_google_play_services_enable_text=0x7f050010;
        /**  Title of confirmation dialog informing user they need to enable
        Google Play services in application settings [CHAR LIMIT=40] 
         */
        public static final int common_google_play_services_enable_title=0x7f05000f;
        /**   Requested by string saying which app requested the notification. [CHAR LIMIT=42] 
         */
        public static final int common_google_play_services_error_notification_requested_by_msg=0x7f05000a;
        /**  Button in confirmation dialog for installing Google Play services [CHAR LIMIT=40] 
         */
        public static final int common_google_play_services_install_button=0x7f05000e;
        /**  (For phones) Message in confirmation dialog informing user that
        they need to install Google Play services (from Play Store) [CHAR LIMIT=NONE] 
         */
        public static final int common_google_play_services_install_text_phone=0x7f05000c;
        /**  (For tablets) Message in confirmation dialog informing user that
        they need to install Google Play services (from Play Store) [CHAR LIMIT=NONE] 
         */
        public static final int common_google_play_services_install_text_tablet=0x7f05000d;
        /**  Title of confirmation dialog informing user that they need to install
        Google Play services (from Play Store) [CHAR LIMIT=40] 
         */
        public static final int common_google_play_services_install_title=0x7f05000b;
        /**  Message in confirmation dialog informing the user that they provided an invalid account. [CHAR LIMIT=NONE] 
         */
        public static final int common_google_play_services_invalid_account_text=0x7f050017;
        /**  Title of confirmation dialog informing the user that they provided an invalid account. [CHAR LIMIT=40] 
         */
        public static final int common_google_play_services_invalid_account_title=0x7f050016;
        /**   Title for notification shown when GooglePlayServices needs to be enabled for an
        application to work. [CHAR LIMIT=70] 
         */
        public static final int common_google_play_services_needs_enabling_title=0x7f050009;
        /**  Message in confirmation dialog informing the user that a network error occurred. [CHAR LIMIT=NONE] 
         */
        public static final int common_google_play_services_network_error_text=0x7f050015;
        /**  Title of confirmation dialog informing the user that a network error occurred. [CHAR LIMIT=40] 
         */
        public static final int common_google_play_services_network_error_title=0x7f050014;
        /**   Title for notification shown when GooglePlayServices needs to be installed
        for an application to work. [CHAR LIMIT=70] 
         */
        public static final int common_google_play_services_notification_needs_installation_title=0x7f050007;
        /**   Title for notification shown when GooglePlayServices needs to be updated for an
        application to work. [CHAR LIMIT=70] 
         */
        public static final int common_google_play_services_notification_needs_update_title=0x7f050008;
        /**   Title for notification shown when GooglePlayServices is unavailable [CHAR LIMIT=42] 
         */
        public static final int common_google_play_services_notification_ticker=0x7f050006;
        /**  Message in confirmation dialog informing user there is an unknown issue in Google Play
        services [CHAR LIMIT=NONE] 
         */
        public static final int common_google_play_services_unknown_issue=0x7f050018;
        /**  Message in confirmation dialog informing user that date on the device is not correct,
    causing certificate checks to fail. [CHAR LIMIT=NONE] 
         */
        public static final int common_google_play_services_unsupported_date_text=0x7f05001b;
        /**  Message in confirmation dialog informing user that Google Play services is not supported on their device [CHAR LIMIT=NONE] 
         */
        public static final int common_google_play_services_unsupported_text=0x7f05001a;
        /**  Title of confirmation dialog informing user that Google Play services is not supported on their device [CHAR LIMIT=40] 
         */
        public static final int common_google_play_services_unsupported_title=0x7f050019;
        /**  Button in confirmation dialog for updating Google Play services [CHAR LIMIT=40] 
         */
        public static final int common_google_play_services_update_button=0x7f05001c;
        /**  Message in confirmation dialog informing user that they need to update
        Google Play services (from Play Store) [CHAR LIMIT=NONE] 
         */
        public static final int common_google_play_services_update_text=0x7f050013;
        /**  Title of confirmation dialog informing user that they need to update
        Google Play services (from Play Store) [CHAR LIMIT=40] 
         */
        public static final int common_google_play_services_update_title=0x7f050012;
        /**  Sign-in button text [CHAR LIMIT=15] 
         */
        public static final int common_signin_button_text=0x7f05001d;
        /**  Long form sign-in button text [CHAR LIMIT=30] 
         */
        public static final int common_signin_button_text_long=0x7f05001e;
        public static final int fourpicpuzzle=0x7f050042;
        public static final int menu_settings=0x7f05002a;
        /**  Text on a placeholder buy button when Google Play services is not
         available or up-to-date 
         */
        public static final int wallet_buy_button_place_holder=0x7f05001f;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        
         */
        public static final int AppBaseTheme=0x7f040005;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
 Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f040006;
        public static final int CustomTheme=0x7f040009;
        /**  use the Android Light theme as the base for our own theme 
 You could change the scrollbar, checkbox style, anything! 
         */
        public static final int ListDialogTheme=0x7f040008;
        /**  You could change the scrollbar, checkbox style, anything! 
         */
        public static final int SpalshScreen=0x7f040007;
        public static final int Theme_IAPTheme=0x7f040000;
        public static final int WalletFragmentDefaultButtonTextAppearance=0x7f040003;
        public static final int WalletFragmentDefaultDetailsHeaderTextAppearance=0x7f040002;
        public static final int WalletFragmentDefaultDetailsTextAppearance=0x7f040001;
        /** 
         Default style of the wallet fragment that will be used if not set explicitly
         when fragment is created
    
         */
        public static final int WalletFragmentDefaultStyle=0x7f040004;
    }
    public static final class styleable {
        /** Attributes that can be used with a AdsAttrs.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #AdsAttrs_adSize com.soulappsworld.flashlights:adSize}</code></td><td>
    The size of the ad.</td></tr>
           <tr><td><code>{@link #AdsAttrs_adSizes com.soulappsworld.flashlights:adSizes}</code></td><td>
    A comma-separated list of the supported ad sizes.</td></tr>
           <tr><td><code>{@link #AdsAttrs_adUnitId com.soulappsworld.flashlights:adUnitId}</code></td><td> The ad unit ID.</td></tr>
           </table>
           @see #AdsAttrs_adSize
           @see #AdsAttrs_adSizes
           @see #AdsAttrs_adUnitId
         */
        public static final int[] AdsAttrs = {
            0x7f010000, 0x7f010001, 0x7f010002
        };
        /**
          <p>
          @attr description
          
    The size of the ad. It must be one of BANNER, FULL_BANNER, LEADERBOARD,
    MEDIUM_RECTANGLE, SMART_BANNER, WIDE_SKYSCRAPER, or
    &lt;width&gt;x&lt;height&gt;.
    


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name com.soulappsworld.flashlights:adSize
        */
        public static final int AdsAttrs_adSize = 0;
        /**
          <p>
          @attr description
          
    A comma-separated list of the supported ad sizes. The sizes must be one of
    BANNER, FULL_BANNER, LEADERBOARD, MEDIUM_RECTANGLE, SMART_BANNER,
    WIDE_SKYSCRAPER, or &lt;width&gt;x&lt;height&gt;.
    


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name com.soulappsworld.flashlights:adSizes
        */
        public static final int AdsAttrs_adSizes = 1;
        /**
          <p>
          @attr description
           The ad unit ID. 


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name com.soulappsworld.flashlights:adUnitId
        */
        public static final int AdsAttrs_adUnitId = 2;
        /** Attributes that can be used with a MapAttrs.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #MapAttrs_cameraBearing com.soulappsworld.flashlights:cameraBearing}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_cameraTargetLat com.soulappsworld.flashlights:cameraTargetLat}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_cameraTargetLng com.soulappsworld.flashlights:cameraTargetLng}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_cameraTilt com.soulappsworld.flashlights:cameraTilt}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_cameraZoom com.soulappsworld.flashlights:cameraZoom}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_mapType com.soulappsworld.flashlights:mapType}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_uiCompass com.soulappsworld.flashlights:uiCompass}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_uiRotateGestures com.soulappsworld.flashlights:uiRotateGestures}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_uiScrollGestures com.soulappsworld.flashlights:uiScrollGestures}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_uiTiltGestures com.soulappsworld.flashlights:uiTiltGestures}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_uiZoomControls com.soulappsworld.flashlights:uiZoomControls}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_uiZoomGestures com.soulappsworld.flashlights:uiZoomGestures}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_useViewLifecycle com.soulappsworld.flashlights:useViewLifecycle}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_zOrderOnTop com.soulappsworld.flashlights:zOrderOnTop}</code></td><td></td></tr>
           </table>
           @see #MapAttrs_cameraBearing
           @see #MapAttrs_cameraTargetLat
           @see #MapAttrs_cameraTargetLng
           @see #MapAttrs_cameraTilt
           @see #MapAttrs_cameraZoom
           @see #MapAttrs_mapType
           @see #MapAttrs_uiCompass
           @see #MapAttrs_uiRotateGestures
           @see #MapAttrs_uiScrollGestures
           @see #MapAttrs_uiTiltGestures
           @see #MapAttrs_uiZoomControls
           @see #MapAttrs_uiZoomGestures
           @see #MapAttrs_useViewLifecycle
           @see #MapAttrs_zOrderOnTop
         */
        public static final int[] MapAttrs = {
            0x7f010003, 0x7f010004, 0x7f010005, 0x7f010006,
            0x7f010007, 0x7f010008, 0x7f010009, 0x7f01000a,
            0x7f01000b, 0x7f01000c, 0x7f01000d, 0x7f01000e,
            0x7f01000f, 0x7f010010
        };
        /**
          <p>This symbol is the offset where the {@link com.soulappsworld.flashlights.R.attr#cameraBearing}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.soulappsworld.flashlights:cameraBearing
        */
        public static final int MapAttrs_cameraBearing = 1;
        /**
          <p>This symbol is the offset where the {@link com.soulappsworld.flashlights.R.attr#cameraTargetLat}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.soulappsworld.flashlights:cameraTargetLat
        */
        public static final int MapAttrs_cameraTargetLat = 2;
        /**
          <p>This symbol is the offset where the {@link com.soulappsworld.flashlights.R.attr#cameraTargetLng}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.soulappsworld.flashlights:cameraTargetLng
        */
        public static final int MapAttrs_cameraTargetLng = 3;
        /**
          <p>This symbol is the offset where the {@link com.soulappsworld.flashlights.R.attr#cameraTilt}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.soulappsworld.flashlights:cameraTilt
        */
        public static final int MapAttrs_cameraTilt = 4;
        /**
          <p>This symbol is the offset where the {@link com.soulappsworld.flashlights.R.attr#cameraZoom}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.soulappsworld.flashlights:cameraZoom
        */
        public static final int MapAttrs_cameraZoom = 5;
        /**
          <p>This symbol is the offset where the {@link com.soulappsworld.flashlights.R.attr#mapType}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>none</code></td><td>0</td><td></td></tr>
<tr><td><code>normal</code></td><td>1</td><td></td></tr>
<tr><td><code>satellite</code></td><td>2</td><td></td></tr>
<tr><td><code>terrain</code></td><td>3</td><td></td></tr>
<tr><td><code>hybrid</code></td><td>4</td><td></td></tr>
</table>
          @attr name com.soulappsworld.flashlights:mapType
        */
        public static final int MapAttrs_mapType = 0;
        /**
          <p>This symbol is the offset where the {@link com.soulappsworld.flashlights.R.attr#uiCompass}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.soulappsworld.flashlights:uiCompass
        */
        public static final int MapAttrs_uiCompass = 6;
        /**
          <p>This symbol is the offset where the {@link com.soulappsworld.flashlights.R.attr#uiRotateGestures}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.soulappsworld.flashlights:uiRotateGestures
        */
        public static final int MapAttrs_uiRotateGestures = 7;
        /**
          <p>This symbol is the offset where the {@link com.soulappsworld.flashlights.R.attr#uiScrollGestures}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.soulappsworld.flashlights:uiScrollGestures
        */
        public static final int MapAttrs_uiScrollGestures = 8;
        /**
          <p>This symbol is the offset where the {@link com.soulappsworld.flashlights.R.attr#uiTiltGestures}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.soulappsworld.flashlights:uiTiltGestures
        */
        public static final int MapAttrs_uiTiltGestures = 9;
        /**
          <p>This symbol is the offset where the {@link com.soulappsworld.flashlights.R.attr#uiZoomControls}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.soulappsworld.flashlights:uiZoomControls
        */
        public static final int MapAttrs_uiZoomControls = 10;
        /**
          <p>This symbol is the offset where the {@link com.soulappsworld.flashlights.R.attr#uiZoomGestures}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.soulappsworld.flashlights:uiZoomGestures
        */
        public static final int MapAttrs_uiZoomGestures = 11;
        /**
          <p>This symbol is the offset where the {@link com.soulappsworld.flashlights.R.attr#useViewLifecycle}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.soulappsworld.flashlights:useViewLifecycle
        */
        public static final int MapAttrs_useViewLifecycle = 12;
        /**
          <p>This symbol is the offset where the {@link com.soulappsworld.flashlights.R.attr#zOrderOnTop}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.soulappsworld.flashlights:zOrderOnTop
        */
        public static final int MapAttrs_zOrderOnTop = 13;
        /**  Attributes for the WalletFragment &lt;fragment&gt; tag 
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #WalletFragmentOptions_environment com.soulappsworld.flashlights:environment}</code></td><td> Google Wallet environment to use </td></tr>
           <tr><td><code>{@link #WalletFragmentOptions_fragmentMode com.soulappsworld.flashlights:fragmentMode}</code></td><td> Fragment mode </td></tr>
           <tr><td><code>{@link #WalletFragmentOptions_fragmentStyle com.soulappsworld.flashlights:fragmentStyle}</code></td><td> A style resource specifing attributes to customize the look and feel of WalletFragment </td></tr>
           <tr><td><code>{@link #WalletFragmentOptions_theme com.soulappsworld.flashlights:theme}</code></td><td> Theme to be used for the Wallet selector </td></tr>
           </table>
           @see #WalletFragmentOptions_environment
           @see #WalletFragmentOptions_fragmentMode
           @see #WalletFragmentOptions_fragmentStyle
           @see #WalletFragmentOptions_theme
         */
        public static final int[] WalletFragmentOptions = {
            0x7f010011, 0x7f010012, 0x7f010013, 0x7f010014
        };
        /**
          <p>
          @attr description
           Google Wallet environment to use 


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>production</code></td><td>1</td><td></td></tr>
<tr><td><code>sandbox</code></td><td>0</td><td></td></tr>
<tr><td><code>strict_sandbox</code></td><td>2</td><td></td></tr>
</table>
          <p>This is a private symbol.
          @attr name com.soulappsworld.flashlights:environment
        */
        public static final int WalletFragmentOptions_environment = 1;
        /**
          <p>
          @attr description
           Fragment mode 


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>buyButton</code></td><td>1</td><td></td></tr>
<tr><td><code>selectionDetails</code></td><td>2</td><td></td></tr>
</table>
          <p>This is a private symbol.
          @attr name com.soulappsworld.flashlights:fragmentMode
        */
        public static final int WalletFragmentOptions_fragmentMode = 3;
        /**
          <p>
          @attr description
           A style resource specifing attributes to customize the look and feel of WalletFragment 


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          <p>This is a private symbol.
          @attr name com.soulappsworld.flashlights:fragmentStyle
        */
        public static final int WalletFragmentOptions_fragmentStyle = 2;
        /**
          <p>
          @attr description
           Theme to be used for the Wallet selector 


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>holo_dark</code></td><td>0</td><td></td></tr>
<tr><td><code>holo_light</code></td><td>1</td><td></td></tr>
</table>
          <p>This is a private symbol.
          @attr name com.soulappsworld.flashlights:theme
        */
        public static final int WalletFragmentOptions_theme = 0;
        /**  Attributes that may be specified in a style resource to customize the look and feel of
         WalletFragment 
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #WalletFragmentStyle_buyButtonAppearance com.soulappsworld.flashlights:buyButtonAppearance}</code></td><td> Appearance of the buy button.</td></tr>
           <tr><td><code>{@link #WalletFragmentStyle_buyButtonHeight com.soulappsworld.flashlights:buyButtonHeight}</code></td><td> Height of the buy button.</td></tr>
           <tr><td><code>{@link #WalletFragmentStyle_buyButtonText com.soulappsworld.flashlights:buyButtonText}</code></td><td> Text on the buy button.</td></tr>
           <tr><td><code>{@link #WalletFragmentStyle_buyButtonWidth com.soulappsworld.flashlights:buyButtonWidth}</code></td><td> Width of the buy button.</td></tr>
           <tr><td><code>{@link #WalletFragmentStyle_maskedWalletDetailsBackground com.soulappsworld.flashlights:maskedWalletDetailsBackground}</code></td><td> Masked wallet details background </td></tr>
           <tr><td><code>{@link #WalletFragmentStyle_maskedWalletDetailsButtonBackground com.soulappsworld.flashlights:maskedWalletDetailsButtonBackground}</code></td><td> "Change" button background in masked wallet details view </td></tr>
           <tr><td><code>{@link #WalletFragmentStyle_maskedWalletDetailsButtonTextAppearance com.soulappsworld.flashlights:maskedWalletDetailsButtonTextAppearance}</code></td><td> TextAppearance for the "Change" button in masked wallet details view </td></tr>
           <tr><td><code>{@link #WalletFragmentStyle_maskedWalletDetailsHeaderTextAppearance com.soulappsworld.flashlights:maskedWalletDetailsHeaderTextAppearance}</code></td><td> TextAppearance for headers describing masked wallet details </td></tr>
           <tr><td><code>{@link #WalletFragmentStyle_maskedWalletDetailsLogoImageType com.soulappsworld.flashlights:maskedWalletDetailsLogoImageType}</code></td><td> Type of the wallet logo image in masked wallet details view </td></tr>
           <tr><td><code>{@link #WalletFragmentStyle_maskedWalletDetailsLogoTextColor com.soulappsworld.flashlights:maskedWalletDetailsLogoTextColor}</code></td><td> Color of the Google Wallet logo text in masked wallet details view </td></tr>
           <tr><td><code>{@link #WalletFragmentStyle_maskedWalletDetailsTextAppearance com.soulappsworld.flashlights:maskedWalletDetailsTextAppearance}</code></td><td> TextAppearance for masked wallet details </td></tr>
           </table>
           @see #WalletFragmentStyle_buyButtonAppearance
           @see #WalletFragmentStyle_buyButtonHeight
           @see #WalletFragmentStyle_buyButtonText
           @see #WalletFragmentStyle_buyButtonWidth
           @see #WalletFragmentStyle_maskedWalletDetailsBackground
           @see #WalletFragmentStyle_maskedWalletDetailsButtonBackground
           @see #WalletFragmentStyle_maskedWalletDetailsButtonTextAppearance
           @see #WalletFragmentStyle_maskedWalletDetailsHeaderTextAppearance
           @see #WalletFragmentStyle_maskedWalletDetailsLogoImageType
           @see #WalletFragmentStyle_maskedWalletDetailsLogoTextColor
           @see #WalletFragmentStyle_maskedWalletDetailsTextAppearance
         */
        public static final int[] WalletFragmentStyle = {
            0x7f010015, 0x7f010016, 0x7f010017, 0x7f010018,
            0x7f010019, 0x7f01001a, 0x7f01001b, 0x7f01001c,
            0x7f01001d, 0x7f01001e, 0x7f01001f
        };
        /**
          <p>
          @attr description
           Appearance of the buy button. Must be one of "classic", "grayscale" and "monochrome" 


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>classic</code></td><td>1</td><td></td></tr>
<tr><td><code>grayscale</code></td><td>2</td><td></td></tr>
<tr><td><code>monochrome</code></td><td>3</td><td></td></tr>
</table>
          <p>This is a private symbol.
          @attr name com.soulappsworld.flashlights:buyButtonAppearance
        */
        public static final int WalletFragmentStyle_buyButtonAppearance = 3;
        /**
          <p>
          @attr description
           Height of the buy button. This includes an 8dp padding (4dp on each side) used for
             pressed and focused states of the button. The value can be a specific height, e.g.
             "48dp", or special values "match_parent" and "wrap_content". 


          <p>May be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
<p>May be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>match_parent</code></td><td>-1</td><td></td></tr>
<tr><td><code>wrap_content</code></td><td>-2</td><td></td></tr>
</table>
          <p>This is a private symbol.
          @attr name com.soulappsworld.flashlights:buyButtonHeight
        */
        public static final int WalletFragmentStyle_buyButtonHeight = 0;
        /**
          <p>
          @attr description
           Text on the buy button. Must be one of "buy_with_google", "buy_now" and "book_now" 


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>buy_with_google</code></td><td>1</td><td></td></tr>
<tr><td><code>buy_now</code></td><td>2</td><td></td></tr>
<tr><td><code>book_now</code></td><td>3</td><td></td></tr>
</table>
          <p>This is a private symbol.
          @attr name com.soulappsworld.flashlights:buyButtonText
        */
        public static final int WalletFragmentStyle_buyButtonText = 2;
        /**
          <p>
          @attr description
           Width of the buy button. This includes an 8dp padding (4dp on each side) used for
             pressed and focused states of the button. The value can be a specific width, e.g.
             "300dp", or special values "match_parent" and "wrap_content". 


          <p>May be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
<p>May be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>match_parent</code></td><td>-1</td><td></td></tr>
<tr><td><code>wrap_content</code></td><td>-2</td><td></td></tr>
</table>
          <p>This is a private symbol.
          @attr name com.soulappsworld.flashlights:buyButtonWidth
        */
        public static final int WalletFragmentStyle_buyButtonWidth = 1;
        /**
          <p>
          @attr description
           Masked wallet details background 


          <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
          <p>This is a private symbol.
          @attr name com.soulappsworld.flashlights:maskedWalletDetailsBackground
        */
        public static final int WalletFragmentStyle_maskedWalletDetailsBackground = 6;
        /**
          <p>
          @attr description
           "Change" button background in masked wallet details view 


          <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
          <p>This is a private symbol.
          @attr name com.soulappsworld.flashlights:maskedWalletDetailsButtonBackground
        */
        public static final int WalletFragmentStyle_maskedWalletDetailsButtonBackground = 8;
        /**
          <p>
          @attr description
           TextAppearance for the "Change" button in masked wallet details view 


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          <p>This is a private symbol.
          @attr name com.soulappsworld.flashlights:maskedWalletDetailsButtonTextAppearance
        */
        public static final int WalletFragmentStyle_maskedWalletDetailsButtonTextAppearance = 7;
        /**
          <p>
          @attr description
           TextAppearance for headers describing masked wallet details 


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          <p>This is a private symbol.
          @attr name com.soulappsworld.flashlights:maskedWalletDetailsHeaderTextAppearance
        */
        public static final int WalletFragmentStyle_maskedWalletDetailsHeaderTextAppearance = 5;
        /**
          <p>
          @attr description
           Type of the wallet logo image in masked wallet details view 


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>classic</code></td><td>1</td><td></td></tr>
<tr><td><code>monochrome</code></td><td>2</td><td></td></tr>
</table>
          <p>This is a private symbol.
          @attr name com.soulappsworld.flashlights:maskedWalletDetailsLogoImageType
        */
        public static final int WalletFragmentStyle_maskedWalletDetailsLogoImageType = 10;
        /**
          <p>
          @attr description
           Color of the Google Wallet logo text in masked wallet details view 


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name com.soulappsworld.flashlights:maskedWalletDetailsLogoTextColor
        */
        public static final int WalletFragmentStyle_maskedWalletDetailsLogoTextColor = 9;
        /**
          <p>
          @attr description
           TextAppearance for masked wallet details 


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          <p>This is a private symbol.
          @attr name com.soulappsworld.flashlights:maskedWalletDetailsTextAppearance
        */
        public static final int WalletFragmentStyle_maskedWalletDetailsTextAppearance = 4;
    };
}
